#!/usr/bin/env bash
# Analisis estatico: cppcheck (+ MISRA-C si hay reglas) + lizard + flawfinder.
# Los archivos generados por CubeMX se excluyen para no evaluar codigo de vendor.
set -uo pipefail

mkdir -p build/static

SRC=Core/Src
USERSRC=Core/User/Src
INC=Core/Inc
USERINC=Core/User/Inc
MISRA_JSON=/opt/misra-config/misra.json
MISRA_TXT=/opt/misra-config/misra.txt
SUPP=tools/cppcheck/misra_suppressions.txt

EXCLUDES=(
  "$SRC/sysmem.c"
  "$SRC/syscalls.c"
  "$SRC/stm32f1xx_hal_msp.c"
  "$SRC/system_stm32f1xx.c"
)
# Autoexcluir codigo generado por STM32CubeMX/.ioc detectando su banner de
# STMicroelectronics. Asi cubre gpio.c, stm32f1xx_it.c y cualquier periferico
# futuro (adc.c, tim.c, usart.c, ...) sin mantener la lista a mano.
# (Solo se analiza Core/Src, asi que el HAL en Drivers/ queda fuera.)
while IFS= read -r f; do
  [ -n "$f" ] && EXCLUDES+=("$f")
done < <(grep -rlE "STMicroelectronics|Generated by STM32Cube" "$SRC" 2>/dev/null || true)

EXTRA=""
for f in "${EXCLUDES[@]}"; do EXTRA="$EXTRA -i $f"; done

# Detectar si MISRA-C esta disponible (requiere el texto de reglas licenciado)
if [ -f "$MISRA_JSON" ] && [ -f "$MISRA_TXT" ]; then
    echo "✅ MISRA-C habilitado (texto de reglas encontrado)"
    ADDON="--addon=$MISRA_JSON"
else
    echo "⚠️ MISRA-C no disponible (falta config/misra.txt). Analisis base solo."
    ADDON=""
fi

cppcheck \
    --enable=warning,style,performance,portability,unusedFunction \
    --std=c11 --language=c \
    -I "$INC" -I "$USERINC" \
    $ADDON \
    --suppressions-list="$SUPP" \
    --xml --xml-version=2 \
    $EXTRA \
    "$SRC" "$USERSRC" 2> build/static/cppcheck.xml || true

# Falla el pipeline por errores/warning reales o violaciones MISRA-C.
# Se ignora id="misra-config" (aviso de cppcheck de analisis incompleto por
# macros HAL desconocidas, no es una violacion de regla).
# Los estilos menores (p.ej. unusedFunction, constParameterPointer) se
# reportan pero no bloquean (tipicos en codigo embebido / CubeMX).
if grep -E '<error [^>]*severity="(error|warning)"' build/static/cppcheck.xml \
        | grep -iv 'id="misra-config"'; then
    echo "❌ cppcheck reporto errores/warning"
    exit 1
fi
if grep -iE '<error [^>]*id="misra' build/static/cppcheck.xml \
        | grep -iv 'id="misra-config"'; then
    # Por ahora MISRA es reporte (no bloquea): el equipo debe limpiar/derivar
    # las violaciones para IEC 62304. El artefacto cppcheck.xml queda como evidencia.
    echo "⚠️ Violaciones MISRA-C detectadas (reporte, no bloquea el pipeline)"
fi

# Complejidad ciclomatica (util para MISRA Rule 17.1 / IEC 62304)
echo "📊 Complejidad ciclomatica (lizard)..."
lizard "$SRC" "$USERSRC" -C 10 -L 50 -m \
    -x"$SRC/sysmem.c" -x"$SRC/syscalls.c" \
    -x"$SRC/stm32f1xx_hal_msp.c" -x"$SRC/system_stm32f1xx.c" \
    -o build/static/complexity.txt 2>&1 || true

# Analisis de seguridad de codigo (flawfinder)
echo "🔐 flawfinder..."
flawfinder --quiet --minlevel=3 --context --html "$SRC" "$USERSRC" > build/static/flawfinder.html 2>&1 || true

echo "✅ Analisis estatico completado"
