#!/usr/bin/env bash
# Analisis estatico: cppcheck (+ MISRA-C si hay reglas) + lizard + flawfinder.
# Los archivos generados por CubeMX se excluyen automaticamente para no evaluar
# codigo de vendor. Al final se genera un reporte HTML unificado (index.html)
# que consolida todos los hallazgos de forma navegable (ver ci/generate_static_report.py).
set -uo pipefail

mkdir -p build/static

# === MACROS / TOOGLES (configurables desde Jenkins via env) ===
# Por defecto todo activado; un desarrollador puede desactivar partes
# localmente, p.ej.: RUN_FLAWFINDER=0 FLAWFINDER_MINLEVEL=3 bash ci/static_analysis.sh
RUN_CPPCHECK="${RUN_CPPCHECK:-1}"
RUN_MISRA="${RUN_MISRA:-1}"
RUN_COMPLEXITY="${RUN_COMPLEXITY:-1}"
RUN_FLAWFINDER="${RUN_FLAWFINDER:-1}"
FLAWFINDER_MINLEVEL="${FLAWFINDER_MINLEVEL:-1}"

SRC=Core/Src
USERSRC=Core/User/Src
INC=Core/Inc
USERINC=Core/User/Inc
MISRA_JSON=/opt/misra-config/misra.json
MISRA_TXT=/opt/misra-config/misra.txt
SUPP=tools/cppcheck/misra_suppressions.txt

# --- Exclusion de codigo generado por STM32CubeMX (gpio.c, stm32f1xx_it.c, etc.) ---
# Lista fija para archivos de startup que no llevan el banner de ST, mas
# deteccion automatica por el banner "STMicroelectronics"/"Generated by STM32Cube"
# para cubrir cualquier periferico futuro sin mantener la lista a mano.
EXCLUDES=(
  "$SRC/sysmem.c"
  "$SRC/syscalls.c"
  "$SRC/stm32f1xx_hal_msp.c"
  "$SRC/system_stm32f1xx.c"
)
while IFS= read -r f; do
  [ -n "$f" ] && EXCLUDES+=("$f")
done < <(grep -rlE "STMicroelectronics|Generated by STM32Cube" "$SRC" 2>/dev/null || true)

EXTRA=""
for f in "${EXCLUDES[@]}"; do EXTRA="$EXTRA -i $f"; done

# --- MISRA-C (requiere el texto de reglas licenciado) ---
if [ "$RUN_MISRA" = "1" ] && [ -f "$MISRA_JSON" ] && [ -f "$MISRA_TXT" ]; then
    echo "MISRA-C habilitado (texto de reglas encontrado)"
    ADDON="--addon=$MISRA_JSON"
else
    if [ "$RUN_MISRA" != "1" ]; then
        echo "MISRA-C deshabilitado (macro RUN_MISRA=0)"
    else
        echo "MISRA-C no disponible (falta config/misra.txt). Analisis base solo."
    fi
    ADDON=""
fi

# cppcheck escribe el reporte XML a un archivo (no a stderr) para que el
# dashboard lo pueda parsear. Los errores/warning y MISRA se reportan pero
# NO bloquean el pipeline (el equipo debe ir limpiandolos para IEC 62304).
if [ "$RUN_CPPCHECK" = "1" ]; then
cppcheck \
    --enable=warning,style,performance,portability,unusedFunction \
    --std=c11 --language=c \
    -I "$INC" -I "$USERINC" \
    $ADDON \
    --suppressions-list="$SUPP" \
    --xml --xml-version=2 \
    --output-file=build/static/cppcheck.xml \
    $EXTRA \
    "$SRC" "$USERSRC" 2> build/static/cppcheck_progress.txt || true
else
    echo "cppcheck deshabilitado (macro RUN_CPPCHECK=0)"
    printf '<results version="2"></results>\n' > build/static/cppcheck.xml
fi

if grep -E '<error [^>]*severity="(error|warning)"' build/static/cppcheck.xml \
        | grep -iv 'id="misra-config"'; then
    echo "cppcheck reporto errores/warning (reporte, no bloquea)"
fi
if grep -iE '<error [^>]*id="misra' build/static/cppcheck.xml \
        | grep -iv 'id="misra-config"'; then
    echo "Violaciones MISRA-C detectadas (reporte, no bloquea el pipeline)"
fi

# --- Complejidad ciclomatica (lizard) excluyendo CubeMX ---
echo "Complejidad ciclomatica (lizard)..."
LIZ_EXTRA=()
for f in "${EXCLUDES[@]}"; do LIZ_EXTRA+=("-x" "$f"); done
if [ "$RUN_COMPLEXITY" = "1" ]; then
# Reporte legible para revision rapida (umbral CCN > COMPLEXITY_THRESHOLD, longitud > 50)
lizard "${LIZ_EXTRA[@]}" "$SRC" "$USERSRC" -C "${COMPLEXITY_THRESHOLD:-10}" -L 50 \
    > build/static/complexity.txt 2>&1 || true
# XML (formato cppncss) para integracion con Jenkins. Se usa --xml (forma
# larga, estable entre versiones) en lugar de -X. El dashboard parsea el
# reporte de texto (complexity.txt), que es mas robusto.
# Se filtra la linea 'xml-stylesheet' para que el navegador muestre el XML como
# arbol legible; si se deja, el navegador intenta aplicar la XSL remota y la
# pagina aparece en blanco al hacer clic desde el reporte.
lizard "${LIZ_EXTRA[@]}" "$SRC" "$USERSRC" -C "${COMPLEXITY_THRESHOLD:-10}" -L 50 --xml 2>/dev/null \
    | grep -v "xml-stylesheet" > build/static/complexity.xml || true
else
    echo "Complejidad deshabilitada (macro RUN_COMPLEXITY=0)"
    : > build/static/complexity.txt
    : > build/static/complexity.xml
fi

# --- Analisis de seguridad de codigo (flawfinder) ---
# Solo codigo de usuario: toda la carpeta Core/User/** mas los archivos
# principales de aplicacion (Core/Src/main.c y Core/Inc/main.h). Se excluye
# el resto de Core/Src/Core/Inc (p.ej. syscalls.c generado por CubeMX).
echo "flawfinder..."
FF_FILES=()
while IFS= read -r f; do [ -n "$f" ] && FF_FILES+=("$f"); done < <(find Core/User -type f 2>/dev/null || true)
[ -f "Core/Src/main.c" ] && FF_FILES+=("Core/Src/main.c")
[ -f "Core/Inc/main.h" ] && FF_FILES+=("Core/Inc/main.h")
if [ "$RUN_FLAWFINDER" = "1" ]; then
    if [ ${#FF_FILES[@]} -gt 0 ]; then
        flawfinder --quiet --minlevel="$FLAWFINDER_MINLEVEL" --context --html "${FF_FILES[@]}" > build/static/flawfinder.html 2>&1 || true
    else
        echo "flawfinder: no se encontraron archivos de usuario para analizar" > build/static/flawfinder.html
    fi
else
    echo "flawfinder deshabilitado (macro RUN_FLAWFINDER=0, nivel=$FLAWFINDER_MINLEVEL)" > build/static/flawfinder.html
fi

# --- Reporte HTML unificado ---
echo "Generando reporte HTML unificado..."
python3 ci/generate_static_report.py

echo "Analisis estatico completado"
