#!/usr/bin/env bash
# Analisis estatico: cppcheck (+ MISRA-C si hay reglas) + lizard + flawfinder.
# Los archivos generados por CubeMX se excluyen automaticamente para no evaluar
# codigo de vendor. Al final se genera un reporte HTML unificado (index.html)
# que consolida todos los hallazgos de forma navegable (ver ci/generate_static_report.py).
set -uo pipefail

mkdir -p build/static

SRC=Core/Src
USERSRC=Core/User/Src
INC=Core/Inc
USERINC=Core/User/Inc
MISRA_JSON=/opt/misra-config/misra.json
MISRA_TXT=/opt/misra-config/misra.txt
SUPP=tools/cppcheck/misra_suppressions.txt

# --- Exclusion de codigo generado por STM32CubeMX (gpio.c, stm32f1xx_it.c, etc.) ---
# Lista fija para archivos de startup que no llevan el banner de ST, mas
# deteccion automatica por el banner "STMicroelectronics"/"Generated by STM32Cube"
# para cubrir cualquier periferico futuro sin mantener la lista a mano.
EXCLUDES=(
  "$SRC/sysmem.c"
  "$SRC/syscalls.c"
  "$SRC/stm32f1xx_hal_msp.c"
  "$SRC/system_stm32f1xx.c"
)
while IFS= read -r f; do
  [ -n "$f" ] && EXCLUDES+=("$f")
done < <(grep -rlE "STMicroelectronics|Generated by STM32Cube" "$SRC" 2>/dev/null || true)

EXTRA=""
for f in "${EXCLUDES[@]}"; do EXTRA="$EXTRA -i $f"; done

# --- MISRA-C (requiere el texto de reglas licenciado) ---
if [ -f "$MISRA_JSON" ] && [ -f "$MISRA_TXT" ]; then
    echo "MISRA-C habilitado (texto de reglas encontrado)"
    ADDON="--addon=$MISRA_JSON"
else
    echo "MISRA-C no disponible (falta config/misra.txt). Analisis base solo."
    ADDON=""
fi

# cppcheck escribe el reporte XML a un archivo (no a stderr) para que el
# dashboard lo pueda parsear. Los errores/warning y MISRA se reportan pero
# NO bloquean el pipeline (el equipo debe ir limpiandolos para IEC 62304).
cppcheck \
    --enable=warning,style,performance,portability,unusedFunction \
    --std=c11 --language=c \
    -I "$INC" -I "$USERINC" \
    $ADDON \
    --suppressions-list="$SUPP" \
    --xml --xml-version=2 \
    --output-file=build/static/cppcheck.xml \
    $EXTRA \
    "$SRC" "$USERSRC" 2> build/static/cppcheck_progress.txt || true

if grep -E '<error [^>]*severity="(error|warning)"' build/static/cppcheck.xml \
        | grep -iv 'id="misra-config"'; then
    echo "cppcheck reporto errores/warning (reporte, no bloquea)"
fi
if grep -iE '<error [^>]*id="misra' build/static/cppcheck.xml \
        | grep -iv 'id="misra-config"'; then
    echo "Violaciones MISRA-C detectadas (reporte, no bloquea el pipeline)"
fi

# --- Complejidad ciclomatica (lizard) excluyendo CubeMX ---
echo "Complejidad ciclomatica (lizard)..."
LIZ_EXTRA=()
for f in "${EXCLUDES[@]}"; do LIZ_EXTRA+=("-x" "$f"); done
# Reporte legible para revision rapida (umbral CCN > 10, longitud > 50)
lizard "${LIZ_EXTRA[@]}" "$SRC" "$USERSRC" -C 10 -L 50 \
    > build/static/complexity.txt 2>&1 || true
# XML (formato cppncss) para integracion con Jenkins. Se usa --xml (forma
# larga, estable entre versiones) en lugar de -X. El dashboard parsea el
# reporte de texto (complexity.txt), que es mas robusto.
lizard "${LIZ_EXTRA[@]}" "$SRC" "$USERSRC" -C 10 -L 50 --xml \
    > build/static/complexity.xml 2>&1 || true

# --- Analisis de seguridad de codigo (flawfinder) ---
echo "flawfinder..."
flawfinder --quiet --minlevel=3 --context --html "$SRC" "$USERSRC" > build/static/flawfinder.html 2>&1 || true

# --- Reporte HTML unificado ---
echo "Generando reporte HTML unificado..."
python3 ci/generate_static_report.py

echo "Analisis estatico completado"
